version: '2'
services:
  web:
    build: httpd
    image: robertdebock/rundeck-httpd
    env_file: "variables.env"
    ports:
      - 80:80
      - 443:443
  rundeck:
    build: rundeck
    image: robertdebock/rundeck
    env_file: "variables.env"
    volumes:
      - ./data/var/log/rundeck:/var/log/rundeck
      - ./data/var/rundeck:/var/rundeck
      - ./data/var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage
  mysql:
    image: mysql
    container_name: mysql
    env_file: "variables.env"
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
